// Export pages
export '/pages/splash/splash_widget.dart' show SplashWidget;
export '/pages/login/login_widget.dart' show LoginWidget;
export '/pages/forgot_password/forgot_password_widget.dart'
    show ForgotPasswordWidget;
export '/pages/password_reset_successfully/password_reset_successfully_widget.dart'
    show PasswordResetSuccessfullyWidget;
export '/pages/dashboard/dashboard_widget.dart' show DashboardWidget;
export '/pages/settings/settings_widget.dart' show SettingsWidget;
export '/pages/stock_order/stock_order_listing/stock_order_listing_widget.dart'
    show StockOrderListingWidget;
export '/pages/stock_order/stock_order_listing_detail/stock_order_listing_detail_widget.dart'
    show StockOrderListingDetailWidget;
export '/pages/stock_order/order_item_detail/order_item_detail_widget.dart'
    show OrderItemDetailWidget;
export '/pages/stock_order/stock_order_listing_detail_verified/stock_order_listing_detail_verified_widget.dart'
    show StockOrderListingDetailVerifiedWidget;
export '/pages/digita_signature/digita_signature_widget.dart'
    show DigitaSignatureWidget;
export '/pages/stock_order/stock_order_listing_detail_verify_t_a_b/stock_order_listing_detail_verify_t_a_b_widget.dart'
    show StockOrderListingDetailVerifyTABWidget;
export '/pages/stock_order/stock_order_listing_detail_verify_t_a_b_popup/stock_order_listing_detail_verify_t_a_b_popup_widget.dart'
    show StockOrderListingDetailVerifyTABPopupWidget;
export '/pages/stock_order/order_item_detail_panel_no/order_item_detail_panel_no_widget.dart'
    show OrderItemDetailPanelNoWidget;
export '/pages/stock_order/stock_order_scan/stock_order_scan_widget.dart'
    show StockOrderScanWidget;
export '/pages/stock_order/stock_order_verify/stock_order_verify_widget.dart'
    show StockOrderVerifyWidget;
export '/pages/stock_order/stock_order_others/stock_order_others_widget.dart'
    show StockOrderOthersWidget;
export '/pages/stock_transfer/stock_transfer_stock_out/stock_transfer_stock_out_widget.dart'
    show StockTransferStockOutWidget;
export '/pages/stock_transfer/stock_transfer_detail/stock_transfer_detail_widget.dart'
    show StockTransferDetailWidget;
export '/pages/stock_transfer/stock_transfer_out_scan/stock_transfer_out_scan_widget.dart'
    show StockTransferOutScanWidget;
export '/pages/stock_transfer/stock_transfer_stock_in/stock_transfer_stock_in_widget.dart'
    show StockTransferStockInWidget;
export '/pages/stock_transfer_detail_verified/stock_transfer_detail_verified_widget.dart'
    show StockTransferDetailVerifiedWidget;
export '/pages/ongoing_jobs/ongoing_jobs_all/ongoing_jobs_all_widget.dart'
    show OngoingJobsAllWidget;
export '/pages/ongoing_jobs/ongoing_jobs_scanned_jobs/ongoing_jobs_scanned_jobs_widget.dart'
    show OngoingJobsScannedJobsWidget;
export '/pages/ongoing_jobs/ongoing_jobs_scanned_del_by_trans/ongoing_jobs_scanned_del_by_trans_widget.dart'
    show OngoingJobsScannedDelByTransWidget;
export '/pages/ongoing_jobs/ongoing_jobs_scanned_pickup_warehouse/ongoing_jobs_scanned_pickup_warehouse_widget.dart'
    show OngoingJobsScannedPickupWarehouseWidget;
export '/pages/ongoing_jobs/ongoing_jobs_scanned_detail/ongoing_jobs_scanned_detail_widget.dart'
    show OngoingJobsScannedDetailWidget;
export '/pages/ongoing_jobs/chang_items/chang_items_widget.dart'
    show ChangItemsWidget;
export '/pages/ongoing_jobs/ongoing_jobs_others/ongoing_jobs_others_widget.dart'
    show OngoingJobsOthersWidget;
export '/pages/ongoing_jobs_search_items/ongoing_jobs_search_items_widget.dart'
    show OngoingJobsSearchItemsWidget;
export '/pages/wholesale_orders/wholesale_orders_all/wholesale_orders_all_widget.dart'
    show WholesaleOrdersAllWidget;
export '/pages/wholesale_orders/wholesale_all_detail/wholesale_all_detail_widget.dart'
    show WholesaleAllDetailWidget;
export '/pages/wholesale_orders/wholesale_order_stock_out/wholesale_order_stock_out_widget.dart'
    show WholesaleOrderStockOutWidget;
export '/pages/wholesale_orders/wholesale_orders_scanned_order/wholesale_orders_scanned_order_widget.dart'
    show WholesaleOrdersScannedOrderWidget;
export '/pages/wholesale_orders/wholesale_items_detail_d_d_l/wholesale_items_detail_d_d_l_widget.dart'
    show WholesaleItemsDetailDDLWidget;
export '/pages/wholesale_orders/wholesale_items_scan/wholesale_items_scan_widget.dart'
    show WholesaleItemsScanWidget;
export '/pages/wholesale_orders/wholesale_orders_others/wholesale_orders_others_widget.dart'
    show WholesaleOrdersOthersWidget;
export '/pages/rever_items/revert_items/revert_items_widget.dart'
    show RevertItemsWidget;
export '/pages/rever_items/revert_items_scan/revert_items_scan_widget.dart'
    show RevertItemsScanWidget;
export '/pages/rever_items/select_installer/select_installer_widget.dart'
    show SelectInstallerWidget;
export '/pages/rever_items/revert_items_selected/revert_items_selected_widget.dart'
    show RevertItemsSelectedWidget;
export '/pages/rever_items/stock_revert/stock_revert_widget.dart'
    show StockRevertWidget;
export '/pages/defecte_items/defected_items/defected_items_widget.dart'
    show DefectedItemsWidget;
export '/pages/defecte_items/defected_items_action/defected_items_action_widget.dart'
    show DefectedItemsActionWidget;
export '/pages/stock_check/stock_check/stock_check_widget.dart'
    show StockCheckWidget;
export '/pages/stock_check/stock_check_detail/stock_check_detail_widget.dart'
    show StockCheckDetailWidget;
export '/pages/stock_check/stock_check_detail_scan/stock_check_detail_scan_widget.dart'
    show StockCheckDetailScanWidget;
export '/pages/dashboard_installer/dashboard_installer_widget.dart'
    show DashboardInstallerWidget;
export '/pages/reports/reports/reports_widget.dart' show ReportsWidget;
export '/pages/reports/reports_serial_number/reports_serial_number_widget.dart'
    show ReportsSerialNumberWidget;
export '/pages/reports/reports_live_stock/reports_live_stock_widget.dart'
    show ReportsLiveStockWidget;
export '/pages/inst_listing_for_installer/inst_listing_for_installer_widget.dart'
    show InstListingForInstallerWidget;
export '/pages/inst_listing_for_installer_copy/inst_listing_for_installer_copy_widget.dart'
    show InstListingForInstallerCopyWidget;
export '/pages/service/service_list/service_list_widget.dart'
    show ServiceListWidget;
export '/pages/service/service_list_old_photo_tab/service_list_old_photo_tab_widget.dart'
    show ServiceListOldPhotoTabWidget;
export '/pages/service/service_list_scan_tab/service_list_scan_tab_widget.dart'
    show ServiceListScanTabWidget;
export '/pages/service/service_list_detail_tab/service_list_detail_tab_widget.dart'
    show ServiceListDetailTabWidget;
export '/pages/service/service_list_photo_tab_copy1/service_list_photo_tab_copy1_widget.dart'
    show ServiceListPhotoTabCopy1Widget;
export '/testing/testing_widget.dart' show TestingWidget;
export '/pages/service/service_list_photo_tab/service_list_photo_tab_widget.dart'
    show ServiceListPhotoTabWidget;
export '/pages/service/service_list_new_photo_tab/service_list_new_photo_tab_widget.dart'
    show ServiceListNewPhotoTabWidget;
export '/pages/service/service_list_scan_tab_copy/service_list_scan_tab_copy_widget.dart'
    show ServiceListScanTabCopyWidget;
export '/testing_copy/testing_copy_widget.dart' show TestingCopyWidget;
export '/test_listview/test_listview_widget.dart' show TestListviewWidget;
export '/pages/service/service_list_panel_inverter_detail/service_list_panel_inverter_detail_widget.dart'
    show ServiceListPanelInverterDetailWidget;
export '/pages/service/service_list_panel_inverter_photo/service_list_panel_inverter_photo_widget.dart'
    show ServiceListPanelInverterPhotoWidget;
export '/pages/service/service_list_panel_inverter_scan/service_list_panel_inverter_scan_widget.dart'
    show ServiceListPanelInverterScanWidget;
export '/pages/service/service_list_panel_inverter_scan_photo/service_list_panel_inverter_scan_photo_widget.dart'
    show ServiceListPanelInverterScanPhotoWidget;
